Improved the code
There's a bug that needs to be fixed - when running the game.py, it gives the following error when trying to attack or print inventory after the player has moved:

"line 73, in choose_action
    action = available_actions.get(action_input)
AttributeError: 'NoneType' object has no attribute 'get'"